name: Build and Test

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
           java-version: 1.8
                
      - name: Test with Maven
        run: cd /usr/bin/git/home/runner/work/1246/1246
        
      - name: Running Slenium Yujuuuu
        run: mvn exec:java  -Dexec.mainClass=test.Main
         
         
